---
title: "Can we predict voting trends based on individual characteristics?"
subtitle: "My subtitle if needed"
author: 
  - Mahak Jain
thanks: "Code and data are available at: https://github.com/MahakJain74/finalpaper_placeholdername.git."
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "Understanding the demographics of voting is essential for every country to include policies for a larger voter turnout. This paper understands the relationship between the characteristics of an individual such as age, gender, social media usage, internet usage, political engagement, trust in society, and discrimination to predict voting participation and to understand the relationship between them. These findings help implement policies to ensure better voter participation and also understand trends in voter turnout. Keywords: voting, internet, social media, volunteer, gender, toronto residents"

output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#must be filled out: title, author, date, keywords, abstract, and introduction.
library(tidyverse)
library(palmerpenguins)
```

# Introduction
Internet consumption is a worldwide phenomenon. Globally, the number of Internet users increased from only 413 million in 2000 to over 3.4 billion in 2016 alone. The usage and accessibility of internet consumption depend on several factors, differing through socioeconomic factors and demographically. Internet usage has become a prominent part of everyone's daily life, from an accessory to a necessity. In 2019, Canada had an estimated 34.56 million internet users. Over 96.5% of Canadians have access to the internet in their households.

There exists a long tradition of research documents and demographic and psychological determinants of political participation, there exists evidence to suggest that changes in communication technology may play an important role in influencing electoral behavior @mcneal. Web-based and theoretical studies often claim that Internet use can mobilize political participation, while survey-based studies generally conclude that Internet use will normalize political participation @hirzalla.

The Internet may enhance voter information about candidates and elections, and in turn, stimulate increased participation @mcneal. Though many European jurisdictions have established well-developed online voting models, Canada is quickly emerging as an important research case. To date, there have been more instances of remote Internet voting in local Canadian elections than in any other country. There have been more than two million remote Internet voting opportunities in over 90 local Canadian elections. This paper explores internet usage and political engagement with voter participation and turnout in federal, municipal, and provincial voting.



# Data




# Model




# Results

# Discussion

## First discussion point

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Second discussion point

## Third discussion point

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

\appendix

# Appendix {-}


# Additional details


\newpage


# References


